// Destura Template — instantiate a client from config/client.config.js.
//
// Reads template/index.html (the pristine, never-overwritten source)
// plus config/client.config.js, and generates three files:
//   - index.html          (final, deployable static page)
//   - css/client-tokens.css (brand color overrides)
//   - api/knowledge.js     (the chat concierge's knowledge base)
//
// Zero dependencies — plain Node fs/string operations, run with:
//   node scripts/apply-config.js
//
// Re-run any time client.config.js changes; template/index.html is
// never mutated, so the same template reuses cleanly for the next client.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import config from "../config/client.config.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const ICONS = {
  hvac: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2v4M12 18v4M4.9 4.9l2.8 2.8M16.3 16.3l2.8 2.8M2 12h4M18 12h4M4.9 19.1l2.8-2.8M16.3 7.7l2.8-2.8"/></svg>`,
  plumbing: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2.7s6 6.3 6 10.6a6 6 0 0 1-12 0c0-4.3 6-10.6 6-10.6z"/></svg>`,
  electrical: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M13 2 4 14h6l-1 8 9-12h-6z"/></svg>`,
  default: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14.7 6.3a4 4 0 0 1-5.6 5.6L3 18l3 3 6.1-6.1a4 4 0 0 1 5.6-5.6l-3-3-3 3z"/></svg>`,
};

function iconFor(serviceName) {
  const n = serviceName.toLowerCase();
  if (/heat|cool|hvac|furnace|air/.test(n)) return ICONS.hvac;
  if (/plumb|water|drain|leak/.test(n)) return ICONS.plumbing;
  if (/electric|wiring|panel/.test(n)) return ICONS.electrical;
  return ICONS.default;
}

function escapeHtml(str) {
  return String(str).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// Expand a single <!-- REPEAT:key --> ... <!-- END:key --> block using
// `rows`, an array of { TOKEN: value } objects scoped to that block.
function expandRepeat(html, key, rows) {
  const re = new RegExp(`<!-- REPEAT:${key} -->([\\s\\S]*?)<!-- END:${key} -->`);
  const match = html.match(re);
  if (!match) return html;
  const snippet = match[1];
  const expanded = rows
    .map((row) => {
      let s = snippet;
      for (const [token, value] of Object.entries(row)) {
        s = s.split(`{{${token}}}`).join(value);
      }
      return s;
    })
    .join("");
  return html.replace(re, expanded);
}

function replaceScalar(html, tokens) {
  let out = html;
  for (const [token, value] of Object.entries(tokens)) {
    out = out.split(`{{${token}}}`).join(value);
  }
  return out;
}

function buildIndexHtml() {
  let html = readFileSync(join(root, "template", "index.html"), "utf8");

  html = expandRepeat(
    html,
    "services",
    config.services.map((s) => ({
      SERVICE_ICON: iconFor(s.name),
      SERVICE_NAME: escapeHtml(s.name),
      SERVICE_BLURB: escapeHtml(s.blurb),
    }))
  );

  html = expandRepeat(
    html,
    "jobs",
    config.proof.jobs.map((j) => ({
      JOB_TITLE: escapeHtml(j.title),
      JOB_LOCATION: escapeHtml(j.location),
      JOB_CAPTION: escapeHtml(j.caption),
    }))
  );

  html = expandRepeat(
    html,
    "financingBadges",
    config.financing.badges.map((b) => ({ FINANCING_BADGE: escapeHtml(b) }))
  );

  html = expandRepeat(
    html,
    "serviceArea",
    config.business.serviceArea.map((c) => ({ CITY: escapeHtml(c) }))
  );

  html = expandRepeat(
    html,
    "faq",
    config.faq.map((f) => ({ FAQ_Q: escapeHtml(f.q), FAQ_A: escapeHtml(f.a) }))
  );

  html = replaceScalar(html, {
    BUSINESS_NAME: escapeHtml(config.business.name),
    BUSINESS_INITIAL: escapeHtml(config.business.name.charAt(0)),
    TAGLINE: escapeHtml(config.business.tagline),
    HERO_HEADLINE: escapeHtml(config.business.heroHeadline),
    PHONE: escapeHtml(config.business.phone),
    PHONE_HREF: escapeHtml(config.business.phoneHref),
    EMAIL: escapeHtml(config.business.email),
    FOUNDED_YEAR: escapeHtml(config.business.foundedYear),
    LICENSE_NOTE: escapeHtml(config.business.licenseNote),
    SERVICE_AREA_INLINE: escapeHtml(config.business.serviceArea.join(", ")),
    RATING: escapeHtml(config.proof.rating),
    REVIEW_COUNT: escapeHtml(config.proof.reviewCount),
    FINANCING_BLURB: escapeHtml(config.financing.blurb),
    CURRENT_YEAR: String(new Date().getFullYear()),
  });

  writeFileSync(join(root, "index.html"), html);
}

function buildClientTokensCss() {
  const css = `/* GENERATED by scripts/apply-config.js from config/client.config.js — do not hand-edit. */
:root {
  --accent: ${config.brand.accent};
  --accent-dark: ${config.brand.accentDark};
  --accent-tint: ${config.brand.accentTint};
}
`;
  writeFileSync(join(root, "css", "client-tokens.css"), css);
}

function buildKnowledgeJs() {
  const js = `// GENERATED by scripts/apply-config.js from config/client.config.js — do not hand-edit.
// Edit config/client.config.js and re-run the script instead.
export default {
  business: ${JSON.stringify(config.business, null, 2)},
  services: ${JSON.stringify(config.services, null, 2)},
  proof: ${JSON.stringify(
    { rating: config.proof.rating, reviewCount: config.proof.reviewCount, badges: config.proof.badges },
    null,
    2
  )},
  financing: ${JSON.stringify(config.financing, null, 2)},
  faq: ${JSON.stringify(config.faq, null, 2)},
  systemPreamble: \`You are the ${config.business.name} concierge, a chat assistant embedded on their website. ${config.business.name} provides ${config.services.map((s) => s.name).join(", ")} for homeowners in ${config.business.serviceArea.join(", ")}.

Your job: answer visitor questions clearly and briefly, using ONLY the facts provided to you in this system context (business info, services, trust info, financing, FAQ). Never invent pricing, timelines, technologies, or claims not in that data.

Tone: plainspoken, direct, warm but not salesy — no hype, no exclamation points, no "great question!" filler.

Scope: if asked something unrelated to ${config.business.name} or its services, politely decline and steer back to how ${config.business.name} can help or to calling directly.

Booking: whenever the visitor signals they want a quote, want to book a service, or have an emergency, end your message with the literal marker [[BOOK_CTA]] on its own at the very end. Only include it when it's genuinely the right next step — not on every message.

Keep replies short — a few sentences at most. This is a chat, not an essay.\`,
};
`;
  writeFileSync(join(root, "api", "knowledge.js"), js);
}

buildIndexHtml();
buildClientTokensCss();
buildKnowledgeJs();

console.log(`Applied config for "${config.business.name}":`);
console.log("  - index.html");
console.log("  - css/client-tokens.css");
console.log("  - api/knowledge.js");
