// GENERATED by scripts/apply-config.js from config/client.config.js — do not hand-edit.
// Edit config/client.config.js and re-run the script instead.
export default {
  business: {
  "name": "Ridgeline Home Services",
  "heroHeadline": "Trusted HVAC, plumbing & electrical for the Fraser Valley.",
  "tagline": "Heating, cooling, plumbing & electrical — done right the first time.",
  "phone": "(604) 555-0142",
  "phoneHref": "+16045550142",
  "email": "hello@ridgelinehomeservices.ca",
  "foundedYear": "2009",
  "serviceArea": [
    "Abbotsford",
    "Chilliwack",
    "Mission",
    "Langley",
    "Surrey",
    "Maple Ridge"
  ],
  "licenseNote": "Fully licensed, bonded & insured across all trades."
},
  services: [
  {
    "name": "Heating & Cooling",
    "blurb": "Furnace repair, AC installs, heat pumps, and seasonal maintenance plans that keep small problems from becoming expensive ones."
  },
  {
    "name": "Plumbing",
    "blurb": "Leak repair, drain cleaning, water heater installs, and fixture work — done clean, done once."
  },
  {
    "name": "Electrical",
    "blurb": "Panel upgrades, rewiring, EV charger installs, and lighting — licensed electricians, not handymen."
  }
],
  proof: {
  "rating": "4.9",
  "reviewCount": "310",
  "badges": [
    "Licensed & Insured",
    "Bonded",
    "Family-Owned Since 2009"
  ]
},
  financing: {
  "blurb": "Big-ticket jobs shouldn't wait on a bank transfer. Flexible financing is available on system installs and replacements, with same-day approval in most cases.",
  "badges": [
    "0% Financing Available",
    "Same-Day Approval",
    "Flexible Terms"
  ]
},
  faq: [
  {
    "q": "Do you offer emergency service?",
    "a": "Yes — we're available 24/7 for no-heat, no-cool, active leaks, and electrical emergencies. Call anytime."
  },
  {
    "q": "Are you licensed and insured?",
    "a": "Yes, fully licensed, bonded, and insured across HVAC, plumbing, and electrical work."
  },
  {
    "q": "What areas do you serve?",
    "a": "Abbotsford, Chilliwack, Mission, Langley, Surrey, and Maple Ridge — reach out if you're just outside this area, we may still be able to help."
  },
  {
    "q": "Do you offer financing for big jobs?",
    "a": "Yes, flexible financing is available on system installs and replacements, with same-day approval in most cases."
  },
  {
    "q": "How do I book a service call?",
    "a": "Call us directly for anything urgent, or use the chat on this site to get a quote and find a time that works."
  }
],
  systemPreamble: `You are the Ridgeline Home Services concierge, a chat assistant embedded on their website. Ridgeline Home Services provides Heating & Cooling, Plumbing, Electrical for homeowners in Abbotsford, Chilliwack, Mission, Langley, Surrey, Maple Ridge.

Your job: answer visitor questions clearly and briefly, using ONLY the facts provided to you in this system context (business info, services, trust info, financing, FAQ). Never invent pricing, timelines, technologies, or claims not in that data.

Tone: plainspoken, direct, warm but not salesy — no hype, no exclamation points, no "great question!" filler.

Scope: if asked something unrelated to Ridgeline Home Services or its services, politely decline and steer back to how Ridgeline Home Services can help or to calling directly.

Booking: whenever the visitor signals they want a quote, want to book a service, or have an emergency, end your message with the literal marker [[BOOK_CTA]] on its own at the very end. Only include it when it's genuinely the right next step — not on every message.

Keep replies short — a few sentences at most. This is a chat, not an essay.`,
};
